import { Industry } from "@/app/types/industries.types";

export const INDUSTRIES: Industry[] = [
  {
    id: "automotive",
    icon: "car",
    title: "Automotive",
    subtitle: "Components, Assemblies & OEM Suppliers",
    description:
      "End-to-end quality support for Tier-1 and Tier-2 suppliers — from incoming material inspection to final assembly audits aligned with IATF 16949 standards.",
    tags: ["OEM Suppliers", "Tier-1 / Tier-2", "IATF 16949", "Welding QC", "Press Parts"],
    accent: "#284c87",
    href: "/industries/automotive",
    caseStudy: {
      id: "cs-auto-01",
      client: "Leading Tier-1 Auto Supplier, Pune",
      challenge: "High rejection rate at customer end due to dimensional non-conformance in machined parts.",
      result: "Implemented in-process inspection checkpoints & SPC monitoring. Rejection rate dropped significantly within 3 months.",
      metric: "68%",
      metricLabel: "Reduction in rejection rate",
    },
  },
  {
    id: "electronics",
    icon: "circuit",
    title: "Electronics",
    subtitle: "Consumer Electronics, PCB & Components",
    description:
      "Pre-dispatch and incoming inspections for electronics manufacturers — covering PCB assemblies, finished goods, packaging checks, and supplier audits.",
    tags: ["PCB Inspection", "Consumer Electronics", "Component QC", "IPC Standards", "ESD Compliance"],
    accent: "#00a2e9",
    href: "/industries/electronics",
    caseStudy: {
      id: "cs-elec-01",
      client: "Electronics Manufacturer, Chennai",
      challenge: "Customer complaints on cosmetic defects and packaging failures during export shipments.",
      result: "Deployed pre-shipment inspection protocol with AQL sampling. Customer complaints reduced to near-zero in 60 days.",
      metric: "94%",
      metricLabel: "Drop in customer complaints",
    },
  },
  {
    id: "heavy-machinery",
    icon: "gear",
    title: "Heavy Machinery",
    subtitle: "Engineering, Castings & Fabrication",
    description:
      "Dimensional, visual and NDT inspections for castings, forgings, fabricated structures and heavy engineering components across diverse manufacturing setups.",
    tags: ["Castings & Forgings", "Fabrication QC", "NDT Inspection", "Dimensional Checks", "Structural Audits"],
    accent: "#1a3460",
    href: "/industries/heavy-machinery",
    caseStudy: {
      id: "cs-mach-01",
      client: "Heavy Engineering Firm, Coimbatore",
      challenge: "Frequent rework and scrap on large casting orders due to undetected internal defects.",
      result: "Introduced stage-wise inspection with UT and MPI testing. Scrap cost reduced considerably within one quarter.",
      metric: "52%",
      metricLabel: "Reduction in scrap cost",
    },
  },
  {
    id: "consumer-goods",
    icon: "box",
    title: "Consumer Goods",
    subtitle: "Appliances, Packaging & FMCG",
    description:
      "Factory audits, product conformance checks, and packaging inspections for consumer goods brands — ensuring every SKU reaches shelves defect-free.",
    tags: ["Home Appliances", "FMCG", "Packaging QC", "Factory Audits", "AQL Sampling"],
    accent: "#0f7abf",
    href: "/industries/consumer-goods",
    caseStudy: {
      id: "cs-cg-01",
      client: "FMCG Brand, Mumbai",
      challenge: "Inconsistent packaging quality across 4 contract manufacturers leading to returns from modern trade.",
      result: "Standardised inspection checklist deployed across all CMOs. Trade returns reduced and brand consistency improved.",
      metric: "76%",
      metricLabel: "Decrease in trade returns",
    },
  },
  {
    id: "textiles",
    icon: "fabric",
    title: "Textiles & Apparel",
    subtitle: "Fabric, Garments & Technical Textiles",
    description:
      "Pre-production, in-line and final random inspections for textile exporters — covering fabric quality, stitching, measurement, and packing norms.",
    tags: ["Fabric Inspection", "Garment QC", "Measurement Checks", "Export Compliance", "4-Point System"],
    accent: "#33b8ff",
    href: "/industries/textiles",
    caseStudy: {
      id: "cs-tex-01",
      client: "Garment Exporter, Tirupur",
      challenge: "High re-inspection and rework at port of export due to measurement and stitching defects.",
      result: "In-line inspection introduced at critical sewing stages. Export re-inspection instances dropped sharply.",
      metric: "81%",
      metricLabel: "Fewer export re-inspections",
    },
  },
  {
    id: "plastics",
    icon: "layers",
    title: "Plastics & Rubber",
    subtitle: "Moulded Parts, Pipes & Industrial Rubber",
    description:
      "Dimensional and functional inspections for injection-moulded components, rubber seals, hoses, and plastic assemblies used across industries.",
    tags: ["Injection Moulding", "Rubber Components", "Dimensional QC", "Functional Testing", "Supplier Audits"],
    accent: "#284c87",
    href: "/industries/plastics",
    caseStudy: {
      id: "cs-plas-01",
      client: "Plastic Components Supplier, Ahmedabad",
      challenge: "Dimensional variation in moulded parts causing assembly issues at the customer's production line.",
      result: "Process audit and gauge R&R study conducted. Tooling corrections made; assembly rejections eliminated.",
      metric: "100%",
      metricLabel: "Assembly rejections eliminated",
    },
  },
];